---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Install the dependencies
      ansible.builtin.package:
        name:
          - wget
          - git
        state: present
    - name: Installing AWS-CLI 2.x
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
        ln -nsf /usr/local/bin/aws /usr/bin/aws
        rm -rf awscliv2.zip
    - name: Install aws-iam-authenticator
      shell: "{{ item }}"
      with_items:
        - curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
        - chmod +x ./aws-iam-authenticator
        - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
        - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
        - mv aws-iam-authenticator /usr/bin/
    - name: Install Artifactory
      shell: |
        wget -O artifactory-pro.rpm "https://releases.jfrog.io/artifactory/artifactory-pro-rpms/jfrog-artifactory-pro/jfrog-artifactory-pro-[RELEASE].rpm"